// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Sourcetype string

const (
	SourcetypeRTSP   Sourcetype = "RTSP"
	SourcetypeMP4    Sourcetype = "MP4"
	SourcetypeWebcam Sourcetype = "Webcam"
)

func (e *Sourcetype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Sourcetype(s)
	case string:
		*e = Sourcetype(s)
	default:
		return fmt.Errorf("unsupported scan type for Sourcetype: %T", src)
	}
	return nil
}

type NullSourcetype struct {
	Sourcetype Sourcetype `json:"sourcetype"`
	Valid      bool       `json:"valid"` // Valid is true if Sourcetype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourcetype) Scan(value interface{}) error {
	if value == nil {
		ns.Sourcetype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Sourcetype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourcetype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Sourcetype), nil
}

type HeadCountLog struct {
	ID         uuid.UUID          `json:"id"`
	SourceID   uuid.UUID          `json:"source_id"`
	HeadCount  int32              `json:"head_count"`
	CurrentFps float64            `json:"current_fps"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Timestamp  pgtype.Timestamp   `json:"timestamp"`
}

type Snapshot struct {
	ID              int32              `json:"id"`
	SourceID        uuid.UUID          `json:"source_id"`
	ImagePath       string             `json:"image_path"`
	HeadCountAtTime int32              `json:"head_count_at_time"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Source struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Type       Sourcetype         `json:"type"`
	Url        string             `json:"url"`
	FpsTarget  int32              `json:"fps_target"`
	Resolution string             `json:"resolution"`
	Status     bool               `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}
